export const CUSTOM_ATTRIBUTES = [
  "ABSORPTION_ON_HIGH_DAMAGE_TAKEN","ADDITIONAL_ARROWS","ANTI_HEAL_ON_HIT",
  "APOCALYPSE_PROTECTION","ARMOR_PENETRATION","BACKSTAB",
  "BERSERKER_RAGE","BLEED_ON_HIT","BLINK_BACK",
  "BOW_SET_BONUS","CHAIN_LIGHTNING","CLOUD_OF_HARMING",
  "CLOUD_OF_HEALING","CLOUD_OF_SLOW","CONE_BLAST",
  "CRITICAL_DAMAGE","CRITICAL_EXECUTE","CRYSTAL_DAMAGE",
  "CRYSTAL_DEFENCE","DAMAGE_PER_ENEMY_COUNT","DAMAGE_PER_ENEMY_HEARTS",
  "DASH_TRINKET","DEFERRED_DAMAGE","DISABLE_MELEE",
  "DODGE_CHANCE","EARTH_RAISE","EFFECT_GAIN",
  "EXECUTE_DAMAGE","EXTRA_DAMAGE_AGAINST_BOSSES","EXTRA_DAMAGE_BASED_ON_ENEMY_SPEED",
  "FIGHTER_SET_BONUS","GRAVITATIONAL_PULL","HEAL_ON_BLOCK",
  "HEALTH_RESERVATION","HEALTHSTEAL","INCREASED_ARROW_VELOCITY",
  "INCREASED_DAMAGE","INCREASED_MELEE_DAMAGE_PER_MISSING_HEART","INCREASED_PROJECTILE_DAMAGE",
  "KAYLESS_ACE","LIFELINE_SHIELD","MACE_DAMAGE",
  "MACE_DEFENCE","MARK_DETONATE","MELEE_EXPLOSION_CHANCE",
  "MELEE_EXPLOSION_POWER","MORE_DAMAGE_AGAINST_FULL_LIFE","MOVEMENT_ON_HIT_OR_KILL",
  "NECRYONS_CALL","NEGATIVE_EFFECT_IMMUNITY","NEGATIVE_EFFECT_IMMUNITY_CHANCE",
  "ORKOTOS_SHIELD","ORKOTOS_SWORD","PARALYZE_ENEMY",
  "RANGED_EXPLOSION","RANDOMIZED_DAMAGE_TAKEN","REDUCED_DAMAGE_TAKEN",
  "REDUCED_PROJECTILE_DAMAGE_TAKEN","REGEN_ON_DAMAGE_TAKEN","SHIELD_ON_KILL",
  "SIREN_CRY","SLOW_ON_HIT","SOUL_STACKS",
  "SPEED_TRINKET","SPEED_TRINKET_DISCLAIMER","SPELL_CLOUD_PERSISTANCE",
  "SPELL_RANGE","STACKING_DAMAGE","STAFF_OF_TENEBRIS",
  "STEALTH","STEALTH_SET_BONUS","SUMMON_SUPPORT_WOLF",
  "SUPPORT_SET_BONUS","TANK_SET_BONUS","TAUNT",
  "TEST_MM_SKILL","THORNS_DAMAGE","TWINFIRE_DUAL_WIELD",
  "WARDEN_SCREAM","WEAK_ARMOR","WITHER_EFFECT_ON_HIT",
] as const;

export const VANILLA_ATTRIBUTES = [
  "ARMOR","ARMOR_TOUGHNESS","ATTACK_DAMAGE",
  "ATTACK_KNOCKBACK","ATTACK_RANGE","ATTACK_SPEED",
  "KNOCKBACK_RESISTANCE","LUCK","MAX_HEALTH",
  "MAX_HEALTH_INCREASE","MOVEMENT_SPEED","SIZE_INCREASE",
] as const;

export interface AttributeOption {
  name: string;
  category: "Custom" | "Vanilla";
}

export const ALL_ATTRIBUTES: AttributeOption[] = [
  ...CUSTOM_ATTRIBUTES.map(a => ({ name: a, category: "Custom" as const })),
  ...VANILLA_ATTRIBUTES.map(a => ({ name: a, category: "Vanilla" as const })),
];
