export const ENCHANTMENTS = [
  "SHARPNESS","SMITE","BANE_OF_ARTHROPODS","SWEEPING_EDGE",
  "POWER","FLAME","INFINITY","PUNCH",
  "PROTECTION","FIRE_PROTECTION","BLAST_PROTECTION","PROJECTILE_PROTECTION",
  "THORNS","RESPIRATION","AQUA_AFFINITY","DEPTH_STRIDER",
  "FROST_WALKER","SOUL_SPEED","SWIFT_SNEAK",
  "UNBREAKING","MENDING","FIRE_ASPECT","LOOTING",
  "KNOCKBACK","EFFICIENCY","SILK_TOUCH","FORTUNE",
  "FEATHER_FALLING","RIPTIDE","LOYALTY","CHANNELING",
  "IMPALING","PIERCING","MULTISHOT","QUICK_CHARGE",
  "WIND_BURST","BREACH","DENSITY",
] as const;
